print("Enter the following values of the Arithmatic Progression to find nth term")
print("The formula for the nth term in an Arithmatic Progression is nth term = a +d(n-1)")
a = int(input("Enter the first term: "))
d = int(input("Enter the common difference(d): "))
n = int(input("Enter the nth term: "))
print("The value of nth term is: ", a+d*(n-1))